name: Community Bot Runner

on:
  schedule:
    - cron: '0 */5 * * *' # Restart setiap 5 jam agar tidak timeout
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Run Bot
        run: node index.js
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          # Kamu bisa tambah secret lain di sini jika ingin menyembunyikan No Rekening
